version: '3.8'

services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb/data:/var/lib/influxdb2  
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=agaszner
      - DOCKER_INFLUXDB_INIT_PASSWORD=Adam0122
      - DOCKER_INFLUXDB_INIT_ORG=BME
      - DOCKER_INFLUXDB_INIT_BUCKET=Crypto
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=OdQ-k5vYAfDR5VlUS1ZoTBFrwMAGe8REftaDBgKYaXpvvqgHDLB6pTIj3cMvXEgzOkeCxd8ZABGTtT15IbuG-g==
    networks:
      - influxdb-net

networks:
  influxdb-net:
    driver: bridge